CREATE TABLE `transaction_log` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint(20) unsigned NOT NULL COMMENT '用户id',
  `amount` decimal(20,4) NOT NULL DEFAULT '0.0000' COMMENT '金额',
  `type` varchar(55) NOT NULL COMMENT '操作类型',
  `order_id` bigint(20) unsigned NOT NULL COMMENT '关联订单号',
  `source_id` bigint(20) unsigned NOT NULL COMMENT '来源id',
  `channel` varchar(55) NOT NULL COMMENT '资金渠道',
  `source` varchar(55) NOT NULL COMMENT '来源id类型',
  `data_source` varchar(55) NOT NULL COMMENT '数据来源',
  `direction` tinyint(4) NOT NULL COMMENT '资金流向',
  `remark` varchar(255) NOT NULL COMMENT '备注',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `mch_id` varchar(255) DEFAULT '' COMMENT '服务商',
  `sub_mch_id` varchar(255) DEFAULT NULL COMMENT '二级商户号',
  `amount_before` decimal(20,4) DEFAULT '0.0000' COMMENT '变更前余额',
  `deposit_before` decimal(20,4) DEFAULT '0.0000' COMMENT '变更前保证金',
  `coin_before` decimal(20,4) DEFAULT '0.0000' COMMENT '变更前购物金',
  `combine_type` enum('DEFAULT','TRADE_ORDER','PLATFORM_COMMISSION','REFUND','DEPOSIT','SUBSIDY','RECHARGE_WITHDRAW','FROZEN','OTHER') DEFAULT 'DEFAULT' COMMENT '资金类别',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_user_id_type_created_at` (`user_id`,`type`,`created_at`),
  KEY `idx_user_id_combine_created_at` (`user_id`,`combine_type`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=452474817518709449 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='流水明细表'